---
- name: install app (java, maven)
  hosts: web
  become: yes

  tasks:
  - name: Ensure java is present
    apt:
     name: default-jdk
     state: present
  tasks:
  - name: Ensure maven is present
    apt:
     name: maven
     state: present
