---
- name: install app (java, maven)
  hosts: web
  become: yes

  tasks:
  - name: Update all packages to their latest version
    apt:
    name: "*"
    state: latest
    
  - name: Ensure java is present
    apt:
     name: default-jdk
     state: present

  - name: Ensure maven is present
    apt:
     name: maven
     state: present
