---
- name: install app (java, maven)
  hosts: build
  become: yes

  tasks:
  - name: Update all packages to their latest version
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Ensure java is present
    apt:
     name: default-jdk
     state: present

  - name: Ensure maven is present
    apt:
     name: maven
     state: present
  - git:
    repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
     dest: /home
  
