---
- name: install app on build(java, maven)
  hosts: build
  become: yes

  tasks:
  - name: Update all packages to their latest version
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Ensure java is present
    apt:
     name: default-jdk
     state: present

  - name: Ensure maven is present
    apt:
     name: maven
     state: present
  
  - name: Ensure rsync is present
    apt:
     name: rsync
     state: present

  - git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /home/repo
  
  - name: Change the working directory to somedir/ before executing the command.
    shell: mvn package
    args:
      chdir: /home/repo

- name: install app on prod (tomcat)
  hosts: prod
  become: yes

  tasks:
  - name: Update all packages to their latest version
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Ensure tomcat is present
    apt:
     name: tomcat9
     state: present
  
  - name: Ensure tomcat is started
    service:
     name: tomcat9
     state: started

  - name: Ensure rsync is present
    apt:
     name: rsync
     state: present

- name: copy war-file
  hosts: all
  tasks:
   - name: Fetch the file from the build to master
     run_once: yes
     fetch: src=/home/repo/target/hello-1.0.war dest=buffer/ flat=yes
     when: "{{ inventory_hostname == 'build' }}"
   - name: Copy the file from the ansible to nodes
     copy: src=tmp/hello-1.0.war dest=/var/lib/tomcat9/webap
     when: "{{ inventory_hostname == 'prod' }}"


  

